### ISSUE TITLE
discord.gift gets detected

### ISSUE THREAD

**Issue by nikolaischunk** [nikolaischunk/stop-discord-phishing#8] opened 2022-02-03 13:39 UTC
Somehow discord.gift gets detected. the closest matching domains are `ldiscord.gift`, `discord.gifte` and `discord.gifte.com`.

**Comment by nikolaischunk** [comment] 2022-02-03 13:40
@lucapolesel any chance that this is related to your PR?

**Comment by nikolaischunk** [comment] 2022-02-03 13:41
maybe `iscord.gift` ?

**Comment by lucapolesel** [comment] 2022-02-03 13:58
@nikolaischunk should be working fine with my changes since I tested it as well (and it is doing an exact match)

**Comment by nikolaischunk** [comment] 2022-02-03 14:02
it is, `iscord.gift` is generating a positive.

**Comment by lucapolesel** [comment] 2022-02-03 14:25
@nikolaischunk I've tested it with version 0.2.0 and 'iscord.gift' isn't causing a false positive.
We can include both 'iscord.gift' and 'discordapp.co' in the list of domains since from version 0.2.0 we are checking an exact match between the two domains (this didn't happen in the previous version since the library was just checking it with "includes()").
Example:
![Code_JA5NRblDMj](https://user-images.githubusercontent.com/6410701/152361583-ce3a9af6-399c-4492-b37a-e5a63a16d782.png)

Result:
![Code_swAGd5Kfey](https://user-images.githubusercontent.com/6410701/152361613-42b2d1c3-2823-4452-ad16-c778e6afc3a3.png)

**Comment by lucapolesel** [comment] 2022-02-18 10:27
I think we can close this issue since we confirmed that the user was using an older version (pre 0.2.0).

**Closed** 2022-05-04 09:10 UTC
Labels: bug, question
